apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongoexpress
  name: mongoexpress-svc
spec:
  ports:
   - port: 8081
     targetPort: 8081
     nodePort: 30003
  selector:
    app: mongoexpress
  type: LoadBalancer
