apiVersion: v1
kind: Service
metadata:
  labels:
    node: worker
  name: my-svc
spec:
  ports:
  - name: 80-80
    nodePort: 30003
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    node: worker
  type: NodePort
status:
  loadBalancer: {}
