#!/bin/bash


read -p "enter a key : "  your_access_key_id


read -p "enter a secret : " your_secret_access_key


read -p "enter a token : "  your_session_token



export AWS_ACCESS_KEY_ID
export AWS_SECRET_ACCESS_KEY
export AWS_SESSION_TOKEN 

