
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  labels:
    db: mongodb
spec:
  selector:
    matchLabels:
      db: mongodb 
  serviceName: "mongodb-svc"
  replicas: 1 
  minReadySeconds: 10 
  template:
    metadata:
      labels:
        db: mongodb 
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mongodb
        image: mongo
        ports:
        - containerPort:  27017
        volumeMounts:
        - name: mongodb-volume
          mountPath: /data/db
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: DB_USERNAME
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: DB_PASSWORD           
  volumeClaimTemplates:
  - metadata:
      name: mongodb-volume
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "local-path"
      resources:
        requests:
          storage: 8Gi
---
