---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  labels:
    db: mysql
spec:
  selector:
    matchLabels:
      db: mysql 
  serviceName: "mysql-svc"
  replicas: 1 
  minReadySeconds: 10 
  template:
    metadata:
      labels:
        db: mysql 
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mysql
        image: mysql:5.6
        ports:
        - containerPort:  3306
        volumeMounts:
        - name: mysql-volume
          mountPath: /var/lib/mysql
      env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: DB_PASSWORD     
  volumeClaimTemplates:
  - metadata:
      name: mysql-volume
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "mysql-sc"
      resources:
        requests:
          storage: 8Gi
---