apiVersion: batch/v1
kind: Job
metadata:
  name: crm-db-init
  namespace: default
spec:
  backoffLimit: 3

  template:
    spec:
      restartPolicy: Never

      containers:
        - name: mysql-init
          image: mysql:8.0

          env:
            - name: DB_HOST_WRITER
              valueFrom:
                configMapKeyRef:
                  name: crm-config
                  key: DB_WRITER_HOST

            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: crm-config
                  key: DB_NAME

            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: crm-db-secret
                  key: DB_USER

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: crm-db-secret
                  key: DB_PASSWORD

          command:
            - /bin/sh
            - -c
            - |
              echo "Waiting for DB..."

              until mysql -h "$DB_HOST_WRITER" -u "$DB_USER" -p"$DB_PASSWORD" -e "SELECT 1"; do
                echo "DB not ready..."
                sleep 5
              done

              echo "Running schema..."

              mysql \
                -h "$DB_HOST_WRITER" \
                -u "$DB_USER" \
                -p"$DB_PASSWORD" \
                "$DB_NAME" < /schema/schema.sql

          volumeMounts:
            - name: schema-volume
              mountPath: /schema

      volumes:
        - name: schema-volume
          configMap:
            name: crm-schema-file
            items:
              - key: schema.sql
                path: schema.sql
